name: "ONBUILD check"
description: "Check (and fail) if any of the base imagees contain Docker ONBUILD instructions (which is a potential supply chain attack vector)"
inputs:
  dockerfile:
    description: "Path to the Dockerfile. (default ./Dockerfile)"
    required: true
    default: "Dockerfile"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      with:
        persist-credentials: false
    - name: Run check
      id: run-check
      shell: bash
      run: |
        echo "Checking $DOCKERFILE"

        images=$(awk '/\s*FROM / { print $2 }' $DOCKERFILE)

        if [[ -z $images ]]; then
            echo "No FROM directives found, exiting"
            exit 0
        fi

        for img in $images; do
            echo "Pulling and checking $img"
            docker pull $img
            onbuilds=$(docker inspect $img | jq -r '.[].Config.OnBuild | length')
            if (( onbuilds != 0 )); then
                echo "$img has ONBUILDs, and that's probably not a good thing"
                exit 1
            fi
        done

        echo "All Good! 😎"
      env:
        DOCKERFILE: ${{ inputs.dockerfile }}
    