name: "ONBUILD check"
description: "Check (and fail) if any of the base imagees contain Docker ONBUILD instructions (which is a potential supply chain attack vector)"
inputs:
  dockerfile:
    description: "Path to the Dockerfile. (default ./Dockerfile)"
    required: true
    default: "Dockerfile"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Run check
      id: run-check
      shell: bash
      run: |
        ./dostuff.sh
      env:
        DOCKERFILE: ${{ github.event.inputs.dockerfile }}
    